# docker-compose.yml
version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: tic-tac-toe-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
