export const PROVIDERS = {
  DATABASE_CONNECTION: Symbol('DATABASE_CONNECTION'),
  GAME_MODEL: Symbol('GAME_MODEL'),
  GAME_REPOSITORY: Symbol('GAME_REPOSITORY'),
  GAME_CREATE_USECASE: Symbol('GAME_CREATE_USECASE'),
  GAME_MAKEMOVE_USECASE: Symbol('GAME_CREATE_USECASE'),
  GAME_GET_FINISHED_USECASE: Symbol('GAME_GET_FINISHED_USECASE'),
};
